export enum ConfirmationStatus {
  UNCONFIRMED = "UNCONFIRMED",
  SOFT_CONFIRMED = "SOFT_CONFIRMED",
  LIKELY_CONFIRMED = "LIKELY_CONFIRMED",
  CONFIRMED = "CONFIRMED",
  DECLINED = "DECLINED",
  PENDING = "PENDING",
}
