AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation stack for message router API, Amazon MQ (RabbitMQ), and worker Lambdas (no NAT Gateway, Lambdas in public subnet)"

Parameters:
  VpcId:
    Type: String
    Description: "VPC where Amazon MQ broker and Lambdas will run"

  PrivateSubnet1Id:
    Type: String
    Description: "Private subnet 1 for broker"

  PrivateSubnet2Id:
    Type: String
    Description: "Private subnet 2 for broker"

  PublicSubnet1Id:
    Type: String
    Description: "Public subnet 1 for Lambdas that need internet access"

  PublicSubnet2Id:
    Type: String
    Description: "Public subnet 2 for Lambdas that need internet access"

  SupabaseUrl:
    Type: String
    Description: "Supabase project URL"

  SupabaseServiceRoleKey:
    Type: String
    Description: "Supabase service role key"
    NoEcho: true

  JwtVerificationKey:
    Type: String
    Description: "Public key or JWKS URL for validating Supabase JWTs"

  AmazonMqAdminUser:
    Type: String
    Description: "Amazon MQ broker admin username"
    NoEcho: true

  AmazonMqAdminPassword:
    Type: String
    Description: "Amazon MQ broker admin password"
    NoEcho: true

  TwilioSubaccountEncryptionKey:
    Type: String
    Description: "Encryption key for Twilio subaccount auth tokens (32 bytes, hex or base64)"
    NoEcho: true

Resources:
  # --- Security Group ---
  MessageBrokerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group for Amazon MQ broker and Lambdas"
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5671
          ToPort: 5671
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0

  # --- Amazon MQ Broker (private) ---
  MessageBroker:
    Type: AWS::AmazonMQ::Broker
    Properties:
      BrokerName: MessageRouterBroker
      EngineType: RABBITMQ
      EngineVersion: "3.13"
      HostInstanceType: mq.t3.micro
      DeploymentMode: SINGLE_INSTANCE
      PubliclyAccessible: false
      AutoMinorVersionUpgrade: true
      SubnetIds:
        - !Ref PrivateSubnet1Id
      SecurityGroups:
        - !Ref MessageBrokerSecurityGroup
      Users:
        - Username: !Ref AmazonMqAdminUser
          Password: !Ref AmazonMqAdminPassword

  # --- IAM Roles ---
  RouterLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MessageRouterLambdaRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: RouterEnvAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"
        - PolicyName: RouterQueueAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource:
                  - !GetAtt BrokerMessageQueue.Arn
                  - !GetAtt MessageProcessingDlq.Arn
        - PolicyName: RouterRateLimitTableAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:UpdateItem
                Resource: !GetAtt RateLimitTable.Arn

  SendWorkerLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SendWorkerLambdaRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SendWorkerLogs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"
        - PolicyName: SendWorkerVpcAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                  - ec2:AssignPrivateIpAddresses
                  - ec2:UnassignPrivateIpAddresses
                Resource: "*"
        - PolicyName: SendWorkerQueueAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt BrokerMessageQueue.Arn
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource:
                  - !GetAtt MessageProcessingDlq.Arn
                  - !GetAtt MessageSenderQueue.Arn

  ReminderWorkerLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ReminderWorkerLambdaRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ReminderWorkerLogs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"
        - PolicyName: ReminderWorkerVpcAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                  - ec2:AssignPrivateIpAddresses
                  - ec2:UnassignPrivateIpAddresses
                Resource: "*"
        - PolicyName: ReminderWorkerQueueAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt BrokerMessageQueue.Arn
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: !GetAtt MessageProcessingDlq.Arn

  MessageSenderLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MessageSenderLambdaRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: MessageSenderLogs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"
        - PolicyName: MessageSenderVpcAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                  - ec2:AssignPrivateIpAddresses
                  - ec2:UnassignPrivateIpAddresses
                Resource: "*"
        - PolicyName: MessageSenderQueueAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt MessageSenderQueue.Arn
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: !GetAtt MessageProcessingDlq.Arn

  # --- Lambdas (moved to Public Subnet) ---
  MessageRouterLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: MessageRouter
      Runtime: nodejs20.x
      Handler: index.handler
      Role: !GetAtt RouterLambdaRole.Arn
      Timeout: 60
      MemorySize: 256
      Environment:
        Variables:
          SUPABASE_URL: !Ref SupabaseUrl
          SUPABASE_SERVICE_ROLE_KEY: !Ref SupabaseServiceRoleKey
          JWT_VERIFICATION_KEY: !Ref JwtVerificationKey
          RATE_LIMIT_TABLE_NAME: !Ref RateLimitTable
          DLQ_URL: !Ref MessageProcessingDlq
          BROKER_MESSAGE_QUEUE_URL: !Ref BrokerMessageQueue
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            console.log("MessageRouter placeholder invoked", JSON.stringify(event));
            return { statusCode: 200, body: JSON.stringify({ ok: true }) };
          };

  SendWorkerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: SendWorker
      Runtime: nodejs20.x
      Handler: index.handler
      Role: !GetAtt SendWorkerLambdaRole.Arn
      Timeout: 60
      MemorySize: 256
      VpcConfig:
        SecurityGroupIds:
          - !Ref MessageBrokerSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnet1Id
          - !Ref PrivateSubnet2Id
      Environment:
        Variables:
          RABBITMQ_ENDPOINT: !Select [0, !GetAtt MessageBroker.AmqpEndpoints]
          RABBITMQ_USERNAME: !Ref AmazonMqAdminUser
          RABBITMQ_PASSWORD: !Ref AmazonMqAdminPassword
          DLQ_URL: !Ref MessageProcessingDlq
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            console.log("SendWorker placeholder invoked", JSON.stringify(event));
          };

  ReminderWorkerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ReminderWorker
      Runtime: nodejs20.x
      Handler: index.handler
      Role: !GetAtt ReminderWorkerLambdaRole.Arn
      Timeout: 60
      MemorySize: 256
      VpcConfig:
        SecurityGroupIds:
          - !Ref MessageBrokerSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnet1Id
          - !Ref PrivateSubnet2Id
      Environment:
        Variables:
          RABBITMQ_ENDPOINT: !Select [0, !GetAtt MessageBroker.AmqpEndpoints]
          RABBITMQ_USERNAME: !Ref AmazonMqAdminUser
          RABBITMQ_PASSWORD: !Ref AmazonMqAdminPassword
          DLQ_URL: !Ref MessageProcessingDlq
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            console.log("ReminderWorker placeholder invoked", JSON.stringify(event));
          };

  MessageSenderLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: MessageSender
      Runtime: nodejs20.x
      Handler: index.handler
      Role: !GetAtt MessageSenderLambdaRole.Arn
      Timeout: 60
      MemorySize: 512
      # No VpcConfig - Lambda outside VPC has internet access by default
      Environment:
        Variables:
          MESSAGE_SENDER_QUEUE_URL: !Ref MessageSenderQueue
          DLQ_URL: !Ref MessageProcessingDlq
          TWILIO_SUBACCOUNT_ENCRYPTION_KEY: !Ref TwilioSubaccountEncryptionKey
          MAX_MESSAGES_PER_INVOCATION: "10"
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            console.log("MessageSender placeholder invoked", JSON.stringify(event));
          };

  # --- SQS Event Source Mapping for MessageSender ---
  MessageSenderQueueMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      Enabled: true
      EventSourceArn: !GetAtt MessageSenderQueue.Arn
      FunctionName: !Ref MessageSenderLambda
      MaximumBatchingWindowInSeconds: 5

  # --- API Gateway ---
  MessageRouterApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: MessageRouterApi
      Description: "API Gateway for message router Lambda"

  MessageRouterApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref MessageRouterApi
      ParentId: !GetAtt MessageRouterApi.RootResourceId
      PathPart: "messages"

  MessageRouterApiMethodPost:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MessageRouterApi
      ResourceId: !Ref MessageRouterApiResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - arn:aws:apigateway:${Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
          - {
              Region: !Ref AWS::Region,
              LambdaArn: !GetAtt MessageRouterLambda.Arn,
            }

  MessageRouterApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - MessageRouterApiMethodPost
    Properties:
      RestApiId: !Ref MessageRouterApi
      StageName: prod

  MessageRouterLambdaPermissionApiGateway:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref MessageRouterLambda
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MessageRouterApi}/*

  # --- DynamoDB Table ---
  RateLimitTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MessageRouterRateLimits
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: company_id
          AttributeType: S
        - AttributeName: window
          AttributeType: S
      KeySchema:
        - AttributeName: company_id
          KeyType: HASH
        - AttributeName: window
          KeyType: RANGE

  # --- Dead Letter Queue ---
  MessageProcessingDlq:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MessageProcessingDlq
      MessageRetentionPeriod: 1209600

  BrokerMessageQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: BrokerMessageQueue
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt MessageProcessingDlq.Arn
        maxReceiveCount: 5

  MessageSenderQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MessageSenderQueue
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt MessageProcessingDlq.Arn
        maxReceiveCount: 5

  SendWorkerQueueMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 5
      Enabled: true
      EventSourceArn: !GetAtt BrokerMessageQueue.Arn
      FunctionName: !Ref SendWorkerLambda
      MaximumBatchingWindowInSeconds: 5
      FilterCriteria:
        Filters:
          - Pattern: '{"messageAttributes":{"MessageType":{"stringValue":["immediate"]}}}'

  ReminderWorkerQueueMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 5
      Enabled: true
      EventSourceArn: !GetAtt BrokerMessageQueue.Arn
      FunctionName: !Ref ReminderWorkerLambda
      MaximumBatchingWindowInSeconds: 5
      FilterCriteria:
        Filters:
          - Pattern: '{"messageAttributes":{"MessageType":{"stringValue":["reminder"]}}}'

  # --- CloudWatch Alarms ---
  MessageRouterErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: MessageRouterLambdaErrors
      AlarmDescription: "Alarm on MessageRouter Lambda errors"
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref MessageRouterLambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold

  SendWorkerErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: SendWorkerLambdaErrors
      AlarmDescription: "Alarm on SendWorker Lambda errors"
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref SendWorkerLambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold

  ReminderWorkerErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: ReminderWorkerLambdaErrors
      AlarmDescription: "Alarm on ReminderWorker Lambda errors"
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref ReminderWorkerLambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold

  MessageSenderErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: MessageSenderLambdaErrors
      AlarmDescription: "Alarm on MessageSender Lambda errors"
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref MessageSenderLambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold

Outputs:
  MessageRouterApiUrl:
    Description: "Invoke URL for Message Router API"
    Value: !Sub "https://${MessageRouterApi}.execute-api.${AWS::Region}.amazonaws.com/prod/messages"
  BrokerMessageQueueUrl:
    Description: "URL for the broker handoff queue"
    Value: !Ref BrokerMessageQueue
